name: entro
description: App para clientes visualizarem seus ingressos (Ticket Sync)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  connectivity_plus: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/ticketsyhnklogo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  flutter_launcher_icons: ^0.13.1

# Configuração do flutter_launcher_icons
flutter_icons:
  android: true
  ios: false
  image_path: "assets/ticketsyhnklogo.png"
